source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
target 'tinyDict' do

pod 'MGSwipeTableCell'
pod 'BOOLoadMoreController', '1.0.3'
pod 'UITextView+Placeholder', '~> 1.2'
pod 'YYKeyboardManager'
pod 'Aspects'
pod 'UIApplication-ViewControllerHandy'
#pod 'LFURLRouter', '1.0.5'

end
